### PR TITLE
Transaction List Improvement

### PR DESCRIPTION
**Pull request by turizspace**
Apply new designs to transactions list rows based on Mac designs and start including failed payments on list 
Screenshot (17)

### CODE REVIEW

**Comment by turizspace** [comment]
https://github.com/stakwork/sphinx-kotlin-ui/assets/143194249/5e3e4722-c8d6-4883-9058-dd642d339d73

made the changes requested . @tomastiminskas

**Comment by tomastiminskas** [comment]
@turizspace thanks! I will test your changes tomorrow and approve the PR if they work/look as expected. Initially I would say you fixed all the issues I mentioned based on the video.

**Comment by tomastiminskas** [comment]
@turizspace the video looks perfect. But here are some last needed adjustments:

1. I saw you changed the hex code for some colors like `md_theme_light_shadow`, `md_theme_dark_background`, `md_theme_dark_shadow`, `randomColor20`. Those defined colors might be used somewhere else in the app, so by changing the hex color you might be affecting the UI of other views of the apps. If the hex color you need to use was not already defined in an existing color, then you need to create new colors.

2. It seems you did changes on TransactionDto on sphinx-kotlin-core submodule. But those changes were not included in the PR. Not sure how it works when working with submodules. But I guess you need to fork that repo as well and push here the reference of the commit on the sphinx-kotlin-core. Or if the changes are simple you can add a screenshot here so I can replicate them to test locally

Thanks in advance

**Comment by tomastiminskas** [comment]
@turizspace I added error_message on TransactionDto, so forget about item 2. As soon as you fixed item 1 I will merge PR and ask @tomsmith8 to process the pmt

**Comment by turizspace** [comment]
@tomastiminskas i have made these changes . . :)

**Pull request merged**
